In [21]:
# Linh Luong
# Please run the code in each block one by one to execute each program. 
# I also submited my_secret file and module to calculate interest. Please download and put them all together in your python working environment

'''
1. Python Basics Review - 10%
Write a Python program that calculates the factorial of a number given from a user input.
Write a python program that takes input from the user and checks if a given string is a palindrome.
Write a python script that takes a string input from the user and splits the characters into a list and prints them. 

'''
# Python program that calculates the factorial of a number given from a user input

try:
    factorial = 1 # set factorial variable to default 1
    while True: # Start the loop to make sure user give the right input, number can't be negative 
        
        num = int(input("Enter factorial number: ")) # ask user for input and make sure it's integer input, if string it will give error
        value = num # set value variable to store the innitial number for printing purpose
        if num < 0: # set condition if number is negative then print this line
            print("Factorial cannot be negative number. Please choose again.")
        elif num == 0: # if user input is 0 then break the loops and factorial result will be default as 1
            break
        else: # if user input is > 0 then break the loop
            break

    while num > 0:  # while loop to start calculating factorial number if input > 0
        factorial *=num # factorial multiply with given number
        num -= 1 # decrease number value 1 each time till 0

    print(f"factorial number of {value} is {factorial}") # print out result statement
    
except ValueError : # when user input string value but not number it will print out this line and end the program
    print("Please enter number not string.")
    


factorial number of 5 is 120


In [23]:
# python program that takes input from the user and checks if a given string is a palindrome.

def palindrome(text): # define function to check if a given string is a palindrome by taking the string as parameter
    sortText = "".join(text.split()).lower() # define a variable to join the orignial message, get rid of space and set them in lowercase.
    reverseText = sortText[::-1] # slicing backward the text and store to reverseText
    return reverseText == text # return the boolean value to the function when comparing original string with palindrome string. If they are the same then return True, otherwise return False.

text = input("Enter your phrases or sentences to check for palindrome: ") # promt user for string input 

if palindrome(text): # use if condition and call palindrome function. If return value is True then print output accordingly
    print(f"'{text}' is a palindrome!")
else:  
    print(f"'{text}' is not a palindrome!")


'no radar' is not a palindrome!


In [25]:
# python script that takes a string input from the user and splits the characters into a list and prints them.

text = input("Enter your String input: ")  # promt user for input

charList = [] # create a list to store characters
for i in range(len(text)): # for loop to loop through the text 
    charList.append(text[i]) # add each charaters from string input to charList 

print(charList) # print all the characters from the string that stored in the charList

['l', 'o', 'v', 'e', ' ', 'y', 'o', 'u']


In [26]:
'''
2. Built-In Functions and Modules - 10%
Working with Built-In Functions:
●	Write a Python script that uses built-in functions to process a list of integers. Use max, min, sum, sort functions.

'''
import string # import string package
numList = [] # list to contain user integer

while True: # loop to prompt user for input
    num = input("Enter the number for your list (to exit give string input or any key but number): ")
    if not num.isalpha() and num not in string.punctuation: # condition to check for input is not string or contain any punctuation 
        numList.append(int(num)) # convert input to int type and add to the list
    else:
        break # if user press any key but number then break the loop

print(f"Your integer list: {(numList)}")    # print the list
print(f"Your max integer is: {max(numList)}")  # print the highest value 
print(f"Your min integer is: {min(numList)}") # print the lowest value 
print(f"The sum of your integer list is: {sum(numList)}") # print the sum of all the integer in the list
sortList = sorted(numList) # sort the list in ascending order
print(f"Your interger list sort in ascending order: {sortList}") # print the sorted list

Your integer list: [25, 125, 215, 215, 44, 556, 4]
Your max integer is: 556
Your min integer is: 4
The sum of your integer list is: 1184
Your interger list sort in ascending order: [4, 25, 44, 125, 215, 215, 556]


In [33]:
# to make it simple i set a fix number for testing purpose instead of asking user for input. Feel free to adjust the number in the code.

'''
3. Using Modules - 10%
●	Create a Python module that includes functions for calculating simple interest and compound interest.
●	Write a script that imports and uses the module created before to perform the interest calculations
'''
import Interest_calculate # import the module

principal_amount = 2000 # set principal amount
interest_rate = 4 # set interest rate
time_period = 2 # set time period

simpleInterest = Interest_calculate.calculate_simple_interest(principal_amount, interest_rate, time_period) # call module and function to calculate simple interest

compound_interest = Interest_calculate.calculate_compound_interest(principal_amount, interest_rate, time_period) # call module and function to calculate compound interest

# print the out put for everything
print("Principal amount = ", principal_amount) 
print("Interest rate = ", interest_rate)
print("Time period  = ", time_period)
print("Simple Interest = ", simpleInterest)
print("Compound Interest = ", round(compound_interest, 1))

Principal amount =  2000
Interest rate =  4
Time period  =  2
Simple Interest =  160.0
Compound Interest =  163.2


In [10]:
'''
4. Data Structures  - 15%

Data Manipulation with Lists, Dictionaries, and Strings
Write a Python program that performs the following operations on lists, dictionaries, and strings:
○	Create a list containing at least five elements.
○	Add two new elements to the list.
○	Remove one element from the list.
○	Create a dictionary with at least three key-value pairs.
○	Add a new key-value pair to the dictionary.
○	Remove one key-value pair from the dictionary.
○	Create a string with the value “Hello World”. 
○	Use uppercase and lowercase functions to convert it. 
○	Call the split method on the string to print a list of substrings. 

'''
list = [] # create an empty list to store elements
for i in range(5): # use for loop to ask user for 5 input for the list
    elem = input(f"What's your {i +1} element to add to the list? ")
    list.append(elem)
print("This is your list", list) # print out the list to make sure all your elements were added to the list

for i in range(2): # loop again to ask user for 2 extra element to add to the list
    add = input("What is your {i +1} element to add extra to this list? ")
    list.append(add)

print("Your list after adding two extra elements", list)
try: # try except function to throw out the error 
    while True: # loop to prompt user for input
        num = int(input(f"Enter the index element you want to remove from your list (0 - {len(list) - 1}): ")) # ask for index number 
        if num >= 0 and num<len(list): # condition to check for input is in the range of the list 
            list.pop(num) # take out the element base on the index number
            break # break the loop
        else:
            print("Wrong input, please choose index number only") # if user input number out of index range, prompt user to input again till it within the range
except ValueError:
    print("Wrong input, please enter number only") # if user input string or anything but number then print out this error and end the program
   
print("Your list after taking out the element: ", list) # print the list again with element remove to check if you remove the right element

# ____________________________________________________end of list program__________________________________________________________________________________ 

dict = {} # create an empty dictionary
for i in range(3): # use for loop to ask user for 3 pair of key and value to add to dictionary
    key = input(f"What's your {i +1} key for the dictionary? ") # ask for key input
    value = input(f"What's your {i +1} value for the dictionary? ") # ask for value input
    dict[key] = value # insert key:value to the dictionary
    
print("This is your dictionary", dict)    # print the dictionary to check if all key-value added correctly

rem = input("Choose the key you want to remove from your dictionary: ") # ask user for the key they want to remove from the dictionary
if rem in dict: # check if the key in the dictionary
    del dict[rem] # delete the key from dictionary if it's in there
    print("Your dictionary after removing one key: ", dict) # print out the dictionary again to check if key:value was removed correctly
else: # if not print out this message
    print("key not in the dictionary")    
 
 
#______________________________________________________end of dictionary program______________________________________________________________________________

string = "Hello World" # create the string that hold value Hello World
upper = string.upper() # call upper case on string
lower = string.lower() # call lower case on string 
stringsplit = string.split() # split the string and store in a list
print("String: ", string) # print string
print("String UPPER case: ", upper) # print string in upper case
print("Sring lower case: ", lower) # print string in lower case
print("String after splitting: ", stringsplit) # print string after splitting into substrings

This is your list ['linh', '21', '343', 'faad', '421']
Your list after adding two extra elements ['linh', '21', '343', 'faad', '421', '32', '21']
Your list after taking out the element:  ['21', '343', 'faad', '421', '32', '21']
This is your dictionary {'ksad': 'fa', 'kjfda': 'kk', 'linh': 'daf'}
Your dictionary after removing one key:  {'ksad': 'fa', 'kjfda': 'kk'}
String:  Hello World
String UPPER case:  HELLO WORLD
Sring lower case:  hello world
String after splitting:  ['Hello', 'World']


In [12]:
# I put the sba.jason file in the same location with my python working environment. Please put it in your python working environment for easier testing purpose
'''
5. Processing JSON Data - 10%

Extracting and Writing Relevant Information
Develop a Python script that reads JSON data from a file (sba.json) extracts specific information, and writes it to another JSON file. Consider "relevant data" as the following for the provided JSON structure:
●	Extract the information related to the company's location (city, state, country).
●	Extract the names and roles of the founders.
●	Extract information about the products, including product names and categories.
Write the extracted information to a new JSON file in a structured format.

Note: Include comments in your script explaining the criteria you used to determine the "relevant data" and the structure of the new JSON file.

'''
import json

company_data = {} # company dictionary to store information to dump to json file later

#company_data['company'] = [] # define key: 'company' and store value as an empty list to add value for later.

with open("sba.json", 'r') as file: # open the json file
    jsonfile = json.load(file) # load json file to python
    
    for key, value in jsonfile.items(): # for loops to loop through jsonfile and search for key and value
        if key == 'location': # condition if the key is location then execute the code 
            print(f"Company location: ")        # print out title company location
            print(f"City: {value['city']} - State: {value['state']} - Country: {value['country']}") # extract data for company location : city, state and country
            company_data['location'] = value # set 'location' as key and add the extracted data as value and store in company data dictionary
            print() # print empty space for clearer view
            
        elif key == 'founders': # elif condition when the key is 'founders'
            print("Founders: ") # print title
            company_data['founders'] = [] # define the key 'founders' and set value as an empty list to add extracted data later
            
            for i in range(len(value)): # loops through the value list in the key 'founders'
                person = {} # create a person dictionary to store the founder information 
                print(f"name: {value[i]['name']} - role: {value[i]['role']}") # extract required data: name and role of the founders
                person['name'] = value[i]['name'] # create key 'name' add value name of the founder to person dictionary
                person['role'] = value[i]['role'] # create key 'role' add founder role to person dictionary
                company_data['founders'].append(person) # set the key as 'founders' for company_data and append all the data created in person dictionary into the value list. We will write these data to our json file later 
            print()
    
        elif key == 'products': # condition if the key is 'products'
            company_data['products'] = [] # define the key 'products' and set value as an empty list to add extract data later for company_data dictionary. We gonna use this dictionary to write relevant data for our json file
            
            print("Products:") # print title
            for i in range(len(value)): # the loops is working exactly as the code above for founders with the same purpose. This time we stored extracted data from products and store them in company_data dictionary
                product = {}
                print(f"Product name: {value[i]['product_name']} - category: {value[i]['category']}")
                product['product_name'] = value[i]['product_name'] 
                product['category'] = value[i]['category']
                company_data['products'].append(product)  
            print()
    
    
# this code will create a json file name company_data.json     
with open('company_data.json', 'w') as jsonFile:
    
    print("create company_data.json file")
    print("Loading data into company_data.json file")
    print("Loading..........")

    # The new json file will contain 'location' as key and value are the list of dictionary with ciy state country as keys, 'founders' will be the second key and its value is the list of dictionary with name, role as key. The last key is 'product' which will have value as a list of dictionary with product_name and category as key
    json.dump(company_data, jsonFile) # write all data to json file using dictionary company_data
   

    print("company_data.json file was successfully created")

Company location: 
City: Silicon Valley - State: California - Country: USA

Founders: 
name: John Smith - role: CEO
name: Emily Davis - role: CTO

Products:
Product name: TechGadget X - category: Electronics
Product name: DataAnalyzer Pro - category: Software

create company_data.json file
Loading data into company_data.json file
Loading..........
company_data.json file was successfully created


In [34]:
'''
6. Interacting with Relational Databases: - 10%
●	Establish a connection to the classicmodels database using your preferred SQL client or programming language.
●	Retrieve a list of all tables in the classicmodels database.
●	Execute a simple SELECT query on the customers table to display information of 10 customers.

'''

import mysql.connector # import myqsl connector to connect to database
import my_secrets # import secret file contain username and password. Change the user and password as it fit for your local machine 

# connect with myqsl server 
conn = mysql.connector.connect(
    host= "localhost",
    port= 3306,
    user= my_secrets.mysql_username,
    password= my_secrets.mysql_password,
    database= "classicmodels") 

cursor = conn.cursor() # create cursor to execute sql query

# This code execute query show tables and print out all the name of the table
cursor.execute("SHOW TABLES") # execute query
tables = cursor.fetchall() # fetch all data to tables
print("Tables in classsicmodels database: ")
for table in tables: # for loop to print out each table names
    print(table[0])
print()

# this code block execute select query on customer table to display customer information
cursor.execute("Select * from customers limit 10")
columns = [col[0] for col in cursor.description] # for better view purpose i print out the headline of the column by parsing all column title using cursor description at index 0
print(" | ".join(columns)) # print out the title and separate with | for prettier output
rows = cursor.fetchall() # fetch all row of customers table
for row in rows: # for loop to print out each customers info and using join map | for prettier result
    print("   | ".join(map(str, row)))


Tables in classsicmodels database: 
customer_contact
customer_order
customer_payment
customers
employees
expenses
high_value_customers
logupdate
offices
orderdetails
orders
payments
productlines
products
temp_view
top2003products

customerNumber | customerName | contactLastName | contactFirstName | phone | addressLine1 | addressLine2 | city | state | postalCode | country | salesRepEmployeeNumber | creditLimit
103   | Atelier graphique   | Schmitt   | Carine    | 40.32.2555   | 54, rue Royale   | None   | Nantes   | None   | 44000   | France   | 1370   | 21000.00
112   | Signal Gift Stores   | King   | Jean   | 7025551838   | 8489 Strong St.   | None   | Las Vegas   | NV   | 83030   | USA   | 1166   | 71800.00
114   | Australian Collectors, Co.   | Ferguson   | Peter   | 03 9520 4555   | 636 St Kilda Road   | Level 3   | Melbourne   | Victoria   | 3004   | Australia   | 1611   | 117300.00
119   | La Rochelle Gifts   | Labrune   | Janine    | 40.67.8555   | 67, rue des Cinquante Otages  

In [35]:
'''
7. Database Operations - 10%
Showcase your skills in retrieving and manipulating data from the classicmodels database:
●	Write a SQL query to retrieve the first 10 records from the orders table.
●	Create a new table named high_value_customers that includes customers with a credit limit greater than $50,000 from the customers table.
●	If the column productLine has the value of ‘Motorcycles’ within productlines table, then change the “textDescription” value to 'Motor Bikes.'
●	Write an SQL query to delete all the records from the 'orderdetails' table where the 'orderLineNumber' is equal to 1.
(Hint: Yes, this will delete the first item in EVERY single Order in the orders table.)

'''
cursor = conn.cursor()
cursor.execute("Select * from orders limit 10") # query to select first 10 order 
columns = [col[0] for col in cursor.description] # for better view purpose i print out the headline of the column by parsing all column title using cursor description at index 0
print(" | ".join(columns)) # print out the title and separate with | for prettier output using join
rows = cursor.fetchall() # fetch all row 
for row in rows: # for loop to print out 
    print("   | ".join(map(str, row)))
print()

# for easier testing purpose i write this code to delete the table if it exists    
cursor.execute("SHOW TABLES LIKE 'high_value_customers'")
table_exists = cursor.fetchone()
if table_exists:
    cursor.execute("DROP TABLE IF EXISTS high_value_customers")
    print("Dropped existing high_value_customers table")

# Query code to create table high value customer with credit limit > 50000
create_table_query = "CREATE TABLE IF NOT EXISTS high_value_customers AS SELECT * FROM customers WHERE creditLimit > 50000;"
cursor.execute(create_table_query)
conn.commit() # commit the change to mysql
print("high_value_customers table successfully created")

# Query code to update productlines table iti set Motorcycles to Motor Bikes from textDescription
update_query = "UPDATE productLines SET textDescription = 'Motor Bikes' WHERE productLine = 'Motorcycles';"
cursor.execute(update_query)

# Commit the changes
conn.commit()

orderNumber | orderDate | requiredDate | shippedDate | status | comments | customerNumber
10100   | 2003-01-06   | 2003-01-13   | 2003-01-10   | Shipped   | good   | 363
10101   | 2003-01-09   | 2003-01-18   | 2003-01-11   | Shipped   | Check on availability.   | 128
10102   | 2003-01-10   | 2003-01-18   | 2003-01-14   | Shipped   | None   | 181
10103   | 2003-01-29   | 2003-02-07   | 2003-02-02   | Shipped   | None   | 121
10104   | 2003-01-31   | 2003-02-09   | 2003-02-01   | Shipped   | None   | 141
10105   | 2003-02-11   | 2003-02-21   | 2003-02-12   | Shipped   | None   | 145
10106   | 2003-02-17   | 2003-02-24   | 2003-02-21   | Shipped   | None   | 278
10107   | 2003-02-24   | 2003-03-03   | 2003-02-26   | Shipped   | Difficult to negotiate with customer. We need more marketing materials   | 131
10108   | 2003-03-03   | 2003-03-12   | 2003-03-08   | Shipped   | None   | 385
10109   | 2003-03-10   | 2003-03-19   | 2003-03-11   | Shipped   | Customer requested that FedEx Ground is

In [36]:
# Delete query 
cursor.execute("DELETE FROM orderdetails where orderlineNumber = 1")
print("All orders with orderlinenumber = 1 deleted.")
# Commit the changes
conn.commit()
conn.close()

All orders with orderlinenumber = 1 deleted.


In [37]:
'''
8. Numpy Operations for Arrays- 15%

Numpy Operations:

Write a Python program that performs the following: 
●	Creating NumPy Arrays
    ○	Create a 1D NumPy array from a Python list [2, 4, 6, 8, 10].
    ○	Create a 2D NumPy array from a nested Python list [[1, 2, 3], [4, 5, 6], [7, 8, 9]].
    ○   Check the attributes of both arrays, such as shape, size, and data type.

'''

import numpy as np

# create our array using numpy
arr1d = np.array([2,4,6,8,10])                      # create 1D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 2D 

# print out the array to check we created the array succesfully
print(arr1d) 
print(arr2d)

# check attribute for both arrays
print("array 1D shape: ", arr1d.shape)  # print out shape for array 1D by calling shape method
print("array 1D size: ", arr1d.size)    # print out size for array 1D by calling size method
print("array 1D type: ", arr1d.dtype)   # print out type for array 1D by calling dtype method
print("array 2D shape: ", arr1d.shape)  # print out shape for array 2D by calling shape method
print("array 2D size: ", arr1d.size)    # print out size for array 2D by calling size method
print("array 2D type: ", arr1d.dtype)   # print out type for array 2D by calling dtype method


[ 2  4  6  8 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
array 1D shape:  (5,)
array 1D size:  5
array 1D type:  int32
array 2D shape:  (5,)
array 2D size:  5
array 2D type:  int32


In [38]:
'''
●	Indexing and Slicing
    ○	Access and print the element at index 3 from the 1D array.
    ○	Slice the 2D array to extract the second column.
    ○	Use boolean indexing to filter elements greater than 5 from the 1D array.
    
'''

print("Element at index 3 from the 1D array: ", arr1d[3])       # slicing the result at index 3 in array 1D
print("Second column of the 2D array: ", arr2d[:,1])            # slicing the second column from array 2D
print("Elements greater than 5 in 1D array: ", arr1d[arr1d>5])  # print out only the elements that greater than 5 in 1D array


Element at index 3 from the 1D array:  8
Second column of the 2D array:  [2 5 8]
Elements greater than 5 in 1D array:  [ 6  8 10]


In [39]:
'''
●	Arithmetic Operations
    ○	Perform element-wise addition, subtraction, multiplication, and division on the 1D array.
    ○	Apply the square root function to the 1D array using NumPy.
    
'''
print("Add 2 to array 1d: ", arr1d + 2)                                         # add 2 into array 1D   
print("Subtract 2 from array 1d: ", arr1d - 2)                                  # substract 2 from array 1D 
print("Multiply 2 to array 1d: ", arr1d * 2)                                    # multiply 2 into array 1D 
print("Divide 2 from array 1d: ", (arr1d / 2))                                  # divide 2 from array 1D
print("Square root function apply to 1D array using numpy: ", np.sqrt(arr1d))   # do squareroot on 1D array by calling method sqrt() from numpy

Add 2 to array 1d:  [ 4  6  8 10 12]
Subtract 2 from array 1d:  [0 2 4 6 8]
Multiply 2 to array 1d:  [ 4  8 12 16 20]
Divide 2 from array 1d:  [1. 2. 3. 4. 5.]
Square root function apply to 1D array using numpy:  [1.41421356 2.         2.44948974 2.82842712 3.16227766]


In [17]:
'''
●	Vector Addition
    ○	Create two 1D NumPy arrays: array1 = [1, 2, 3] and array2 = [4, 5, 6].
    ○	Perform vector addition on the two arrays and print the result.
    
'''
# create 2 array using numpy
array1 = np.array([1, 2, 3])                 
array2 = np.array([4, 5, 6])                 

# print both array to make sure we created them right
print(array1)
print(array2)

# perform addition on two arrays and print out the result
print("array1 + array2 = ", array1 + array2) 


[1 2 3]
[4 5 6]
array1 + array2 =  [5 7 9]


In [40]:
'''
●	Matrix Addition
    ○	Create two 2D NumPy arrays:
        ■	matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
        ■	matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
    ○	Perform matrix addition on the two matrices.
'''
# create 2 matrices using numpy
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])   
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])   

# print out two matrices for checking purpose
print(matrix1)
print(matrix2)

# perform matrix addition and print result
print("matrix1 + matrix2 = " ) 
print(matrix1 + matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
matrix1 + matrix2 = 
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [4]:
# For easier testing and execution I divide this problem by blocks. This is the beginning of the code. Please run this block first then follow orders
# If your sql has my_db database already please drop it before testing. If the program keep running just stop it and run again. 

'''
9. Advanced Database Concepts - 10%

You can use sample_data.sql file for the dummy values to insert into the required tables, as the task below iterates. 

Basic Joins Operation: 
    ●	Create a database called my_db in your mysql database.
    ●	Create two tables: students and courses with columns student_id, student_name (VARCHAR), and course_id, course_name (VARCHAR) respectively.
    ●	Insert sample data into both tables. Use variables students_data and courses_data for sample data. 
    ●	Create a third table named student_course_enrollment with columns enrollment_id, student_id, and course_id.
    ●	Insert sample enrollment data to establish relationships between students and courses. 
    ●	Perform a basic join query to retrieve a list of students along with the courses they are enrolled in.
    ●	Print the result of the join query.

'''
import mysql.connector # import myqsl connector to connect to database
import my_secrets # import secret file contain username and pass word change the user and password as it fit on your local machine

# connect with myqsl server 
conn = mysql.connector.connect(
    host= "localhost",
    port= 3306,
    user= my_secrets.mysql_username,
    password= my_secrets.mysql_password,
    ) 

cursor = conn.cursor() # create cursor to execute sql query

# create database my_db and use it
database_name = 'my_db'
cursor.execute(f"CREATE DATABASE IF NOT EXISTS {database_name}")
cursor.execute(f"USE {database_name}")
print("Database successuly created")

# Create table students with columns student_id, student_name (VARCHAR)
cursor.execute("CREATE TABLE IF NOT EXISTS students (student_id INT AUTO_INCREMENT PRIMARY KEY, student_name VARCHAR(255) NOT NULL);")
print("Table students successfully created")

# create table courses with columns course_id, course_name (VARCHAR)
cursor.execute("CREATE TABLE IF NOT EXISTS courses (course_id INT AUTO_INCREMENT PRIMARY KEY, course_name VARCHAR(255) NOT NULL);")
print("Table courses successfully created")
conn.commit()


Database successuly created
Table students successfully created
Table courses successfully created


In [5]:
# insert values into students table
cursor.execute("INSERT INTO students (student_id, student_name) VALUES (1, 'John Doe'), (2, 'Jane Smith'), (3, 'Bob Johnson');")
print("Values inserted into students table")

# insert values into courses table
cursor.execute("INSERT INTO courses (course_id, course_name) VALUES (101, 'Mathematics'), (102, 'History'), (103, 'Computer Science');")
print("Values inserted into courses table")

conn.commit()

Values inserted into students table
Values inserted into courses table


In [6]:
# Create a third table named student_course_enrollment with columns enrollment_id, student_id, and course_id. set foreign key to establish relationship with student_course_enrollment table through student id and course id
cursor.execute("""
               CREATE TABLE IF NOT EXISTS student_course_enrollment (
                   enrollment_id INT PRIMARY KEY, 
                   student_id INT, 
                   course_id INT, 
                   CONSTRAINT `student_fk` FOREIGN KEY (`student_id`) REFERENCES `students` (`student_id`), 
                   CONSTRAINT `course_fk` FOREIGN KEY (`course_id`) REFERENCES `courses` (`course_id`))
                   """)
print("Table successfully created")

# insert values into student_course enrollment table
cursor.execute("INSERT INTO student_course_enrollment (enrollment_id, student_id, course_id) VALUES (1, 1, 101), (2, 1, 102), (3, 2, 103), (4, 3, 101), (5, 3, 103);")
print("Values inserted into student_course_enrollment table ")
conn.commit()

Table successfully created
Values inserted into student_course_enrollment table 


In [7]:
# select statement to join tables and retrieve student_name and course_name
cursor.execute("select student_name, course_name from students join student_course_enrollment using(student_id) join courses using(course_id)")
rows = cursor.fetchall() # fetch all rows from query to python 

# print out the result of query 
for row in rows:
    print(row)
    
conn.close()

('John Doe', 'Mathematics')
('John Doe', 'History')
('Jane Smith', 'Computer Science')
('Bob Johnson', 'Mathematics')
('Bob Johnson', 'Computer Science')
