In [9]:
import numpy as np

dtype = np.dtype(np.int8)

myArray = np.array([1,2,3,4,5])
print(myArray)

myArray[4] = 7

print(myArray)

myArray[0:3] = [2,3,4]

print(myArray)

[1 2 3 4 5]
[1 2 3 4 7]
[2 3 4 4 7]


In [8]:
my_array = np.array([[1,2,3],[4,5,6]])
print(my_array)
print(my_array[:, 1:3])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [11]:
array = np.array(range(1,4))
print(array)

[1 2 3]
